version: "2"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/digipolisgent/ci_config-files-and-scripts/master/chef/.rubocop.yml"
    path: ".rubocop.yml"
  - url: "https://raw.githubusercontent.com/digipolisgent/ci_config-files-and-scripts/master/chef/.foodcritic.yml"
    path: ".foodcritic.yml"

plugins:
  rubocop:
    enabled: true
  foodcritic:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
  fixme:
    enabled: true
  markdownlint:
    enabled: true

exclude_patterns:
- "**/.idea/**/*"
- "**/tests/**/*"
- "**/.vagrant/**/*"
- "**/.kitchen/**/*"
- "/cookbooks"
