driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: false

platforms:
  - name: centos-7
    driver:
      image: centos:7
      chef_version: '13.4.24'
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools openssl openssh-server
